// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkw0cNP9lZTJXVMwQsJF4zXvNWja1S7cQ',
    appId: '1:126996327651:web:2ceb9a7a354b74fd6a29d6',
    messagingSenderId: '126996327651',
    projectId: 'flutterpushnotification-28c6d',
    authDomain: 'flutterpushnotification-28c6d.firebaseapp.com',
    storageBucket: 'flutterpushnotification-28c6d.appspot.com',
    measurementId: 'G-2V95JM9DE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn08qgHbl30CC0FIqTuPxIdfnW82kJqQU',
    appId: '1:126996327651:android:ba250437f00cb4ab6a29d6',
    messagingSenderId: '126996327651',
    projectId: 'flutterpushnotification-28c6d',
    storageBucket: 'flutterpushnotification-28c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmesCLxXBm83j8S3W0jgu4PgxuSDYfvuo',
    appId: '1:126996327651:ios:71648b279e39770c6a29d6',
    messagingSenderId: '126996327651',
    projectId: 'flutterpushnotification-28c6d',
    storageBucket: 'flutterpushnotification-28c6d.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmesCLxXBm83j8S3W0jgu4PgxuSDYfvuo',
    appId: '1:126996327651:ios:71648b279e39770c6a29d6',
    messagingSenderId: '126996327651',
    projectId: 'flutterpushnotification-28c6d',
    storageBucket: 'flutterpushnotification-28c6d.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkw0cNP9lZTJXVMwQsJF4zXvNWja1S7cQ',
    appId: '1:126996327651:web:0bdc542922ef2e0f6a29d6',
    messagingSenderId: '126996327651',
    projectId: 'flutterpushnotification-28c6d',
    authDomain: 'flutterpushnotification-28c6d.firebaseapp.com',
    storageBucket: 'flutterpushnotification-28c6d.appspot.com',
    measurementId: 'G-KL26HXQK1P',
  );
}
